version: '3.8'
services:

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=experiments.schau-wien.at
      - SUBDOMAINS=test1,test2,test3,test4,test5,fergus,sophie,enrique,maxie,kiki,paula
      - VALIDATION=
      - ONLY_SUBDOMAINS=false #optional
      - STAGING=false #optional
    volumes:
      - "${PATH_TO_DIR}/config:/config"
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  nginx-dev:
    image: nginx:latest
    volumes:
      - "${PATH_TO_DIR}/www-dev:/www"
      - "${PATH_TO_DIR}/nginx-dev:/etc/nginx/conf.d"
    ports:
      - 80:80
