version: '3.8'
services:

  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=experiments.schau-wien.at
      - SUBDOMAINS=1,2,3,4,5,6,7,8,9,
      - VALIDATION=http
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - "${PATH_TO_DIR}/config:/config"
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - "${PATH_TO_DIR}/nginx:/etc/nginx/conf.d"
  #     - "${PATH_TO_DIR}/www:/www"
  #   ports:
  #     - 80:80

