version: '3.8'
services:

  nginx:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    # - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
    - 80:80
    - 443:443

  node:
    image: node:12
    user: "node"
    working_dir: /home/node/app
    environment:
    - NODE_ENV=production
    volumes:
    - /mnt/pi/app_data/schau/fergusfettes.github.io/experiments:/home/node/app
    expose:
    - "8081"
    command: "npm start"

#   firefox:
#     image: ffettes/firefox-audio
